/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package matematica;

/**
 *
 * @author Welton
 */
public class Tabuada extends javax.swing.JFrame {

    /**
     * Creates new form Tabuada
     */
    public Tabuada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumaradorSoma = new javax.swing.JTextField();
        txtDenominadorSoma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblResultadoSomar = new javax.swing.JLabel();
        btnResultadoSomar = new javax.swing.JButton();
        txtNumeradorSubtracao = new javax.swing.JTextField();
        txtDenominadorSubtracao = new javax.swing.JTextField();
        btnResultadoSubtracao = new javax.swing.JButton();
        lblResultadoSubtracao = new javax.swing.JLabel();
        txtNumeradorMultiplicacao = new javax.swing.JTextField();
        txtDenominadorMultiplicacao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnResultadoMultiplicar = new javax.swing.JButton();
        lblResultadoMultiplicacao = new javax.swing.JLabel();
        txtNumDivisao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDenDivisao = new javax.swing.JTextField();
        btnResDivisao = new javax.swing.JButton();
        lblResDivisao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mathematics");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel1.setText("Mathematics");

        jLabel2.setText("Soma");

        jLabel3.setText("subtração");

        jLabel4.setText("Multiplicação");

        jLabel5.setText("Divisão");

        txtNumaradorSoma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDenominadorSoma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDenominadorSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDenominadorSomaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("+");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("-");

        lblResultadoSomar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnResultadoSomar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResultadoSomar.setText("=");
        btnResultadoSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoSomarActionPerformed(evt);
            }
        });

        txtNumeradorSubtracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDenominadorSubtracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnResultadoSubtracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResultadoSubtracao.setText("=");
        btnResultadoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoSubtracaoActionPerformed(evt);
            }
        });

        lblResultadoSubtracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNumeradorMultiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDenominadorMultiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("x");

        btnResultadoMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResultadoMultiplicar.setText("=");
        btnResultadoMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoMultiplicarActionPerformed(evt);
            }
        });

        lblResultadoMultiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNumDivisao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("/");

        txtDenDivisao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnResDivisao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResDivisao.setText("=");
        btnResDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResDivisaoActionPerformed(evt);
            }
        });

        lblResDivisao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumaradorSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDenominadorSoma))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNumeradorSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDenominadorSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNumeradorMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDenominadorMultiplicacao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResultadoMultiplicar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultadoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResultadoSomar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultadoSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResultadoSubtracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultadoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(302, 302, 302))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNumDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDenDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResDivisao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumaradorSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDenominadorSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(btnResultadoSomar))
                    .addComponent(lblResultadoSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumeradorSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenominadorSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultadoSubtracao)
                    .addComponent(lblResultadoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeradorMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenominadorMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnResultadoMultiplicar)
                    .addComponent(lblResultadoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDenDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResDivisao)
                    .addComponent(lblResDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDenominadorSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDenominadorSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenominadorSomaActionPerformed

    private void btnResultadoSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoSomarActionPerformed
        int num = Integer.parseInt(txtNumaradorSoma.getText());
        int den = Integer.parseInt(txtDenominadorSoma.getText());
        int soma = num + den;
        String resultado = String.valueOf(soma);
        lblResultadoSomar.setText(resultado);
        txtNumaradorSoma.setText(null);
        txtDenominadorSoma.setText(null);
    }//GEN-LAST:event_btnResultadoSomarActionPerformed

    private void btnResultadoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoSubtracaoActionPerformed
        int num = Integer.parseInt(txtNumeradorSubtracao.getText());
        int den = Integer.parseInt(txtDenominadorSubtracao.getText());
        int subtracao = num - den;
        String resultado = String.valueOf(subtracao);
        lblResultadoSubtracao.setText(resultado);
        txtNumeradorSubtracao.setText(null);
        txtDenominadorSubtracao.setText(null);
    }//GEN-LAST:event_btnResultadoSubtracaoActionPerformed

    private void btnResultadoMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoMultiplicarActionPerformed
        int num = Integer.parseInt(txtNumeradorMultiplicacao.getText());
        int den = Integer.parseInt(txtDenominadorMultiplicacao.getText());
        int multiplicacao = num * den;
        String resultado = String.valueOf(multiplicacao);
        lblResultadoMultiplicacao.setText(resultado);
        txtNumeradorMultiplicacao.setText(null);
        txtDenominadorMultiplicacao.setText(null);
    }//GEN-LAST:event_btnResultadoMultiplicarActionPerformed

    private void btnResDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResDivisaoActionPerformed
        double num = Integer.parseInt(txtNumDivisao.getText());
        double den = Integer.parseInt(txtDenDivisao.getText());
        double divisao = num / den;
        String resultado = String.valueOf(divisao);
        lblResDivisao.setText(resultado);
        txtNumDivisao.setText(null);
        txtDenDivisao.setText(null);

    }//GEN-LAST:event_btnResDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResDivisao;
    private javax.swing.JButton btnResultadoMultiplicar;
    private javax.swing.JButton btnResultadoSomar;
    private javax.swing.JButton btnResultadoSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblResDivisao;
    private javax.swing.JLabel lblResultadoMultiplicacao;
    private javax.swing.JLabel lblResultadoSomar;
    private javax.swing.JLabel lblResultadoSubtracao;
    private javax.swing.JTextField txtDenDivisao;
    private javax.swing.JTextField txtDenominadorMultiplicacao;
    private javax.swing.JTextField txtDenominadorSoma;
    private javax.swing.JTextField txtDenominadorSubtracao;
    private javax.swing.JTextField txtNumDivisao;
    private javax.swing.JTextField txtNumaradorSoma;
    private javax.swing.JTextField txtNumeradorMultiplicacao;
    private javax.swing.JTextField txtNumeradorSubtracao;
    // End of variables declaration//GEN-END:variables
}
